services:
  web-server:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: web-container 
    ports:
      - "8888:8888"
    volumes:
      - .:/home/node/app 
      - /home/node/app/node_modules 
    environment:
      - NODE_ENV=development
      - DATABASE_URL=postgres://postgres:password@db:5432/mydatabase
    depends_on:
      - db

  db:
    image: postgres:15-alpine
    container_name: postgres-container
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mydatabase
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - "2345:2345"

volumes:
  postgres-data:
